命令稿啟動於 2018年03月15日 下午 09:07:02
]0;~
[32mUSER@X556UR6 [33m~[0m
$ wham[K[Koami; pwd
USER
/home/USER
]0;~
[32mUSER@X556UR6 [33m~[0m
$ gt[Kit config -l
user.email=e24066195@ncku.edu.com.tw
user.name=E24066195
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
]0;~
[32mUSER@X556UR6 [33m~[0m
$ git con[K[Klone https://git [K.com/E24066195/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;~
[32mUSER@X556UR6 [33m~[0m
$ exit

命令稿已於 2018年03月15日 下午 09:07:54
 完成