命令稿啟動於 2018年03月15日 下午 08:56:52
]0;~
[32mUSER@X556UR6 [33m~[0m
$ whoami; pwd
USER
/home/USER
]0;~
[32mUSER@X556UR6 [33m~[0m
$ git config -l
user.email=e24066195@ncku.edu.com.tw
user.name=E24066195
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
]0;~
[32mUSER@X556UR6 [33m~[0m
$ git clone h[Khttps://githun[Kb.com/E24066195/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;~
[32mUSER@X556UR6 [33m~[0m
$ exit

命令稿已於 2018年03月15日 下午 08:57:32
 完成